### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::share()

### ISSUE THREAD

**Issue by YannisHeine** [anouarabdsslm/laravel-paypalpayment#100]
Steps Reproducing the bug:

1. Start Fresh Installation Laravel 5.4
2. Install Package (added  "anouar/paypalpayment": "~1.0" to composer.json)
3. Add Providers to Config/App.php
4. Run PHP Artisan in console. [ERROR]

Error Message:

[Symfony\Component\Debug\Exception\FatalThrowableError]
Call to undefined method Illuminate\Foundation\Application::share()

**Comment by marteagam** [comment]
This worked for me:
"require": {
    "anouar/paypalpayment": "~2.0"
}
