### ISSUE TITLE
Fatal error:  Call to undefined method Illuminate\Foundation\Application::share()

### ISSUE THREAD

**Issue by evgeny-birch** [anouarabdsslm/laravel-paypalpayment#101]
Hi!
I am install package through Composer
"require": {
    "anouar/paypalpayment": "~1.0"
}

In composer package, class PaypalpaymentServiceProvider not changed line 45:
$this->app['paypalpayment'] = $this->app->share(function($app)

to:
$this->app->singleton('paypalpayment', function($app)

thanks!

**Comment by anouarabdsslm** [comment]
This bug is fixed
