### ISSUE TITLE
Where to see payment made on the sandbox.paypal.com

### ISSUE THREAD

**Issue by thom7kick** [anouarabdsslm/laravel-paypalpayment#102]
I am getting a response that payment is approved but can't see anything on my paypal sandbox account. How does this work.

**Comment by HapLifeMan** [comment]
You have to create a [sandbox account](https://www.sandbox.paypal.com) then link with your developer account [here] on "Click Here" (https://developer.paypal.com/developer/accounts/) ;)

**Comment by thom7kick** [comment]
@HapLifeMan so when i login to sandbox with the facilitator account i can see payment made using credit card. But i cant see paypal payments. i got the redirect url made payment and got the call back
 `http://whatever.loc/callback?success=true&paymentId=PAY-2J809046DA3584001LDNAP4A&token=EC-73923433HP409401Y&PayerID=24P7C5D9YG8H4`

but i don't see any transaction

**Comment by HapLifeMan** [comment]
You can trust PayPal, you have no reason to see the payment on PayPal. You can retrieve the payment with the API : https://developer.paypal.com/docs/api/payments/#payment_get!

**Comment by thom7kick** [comment]
@HapLifeMan what i did was i went to the developer account and take the buyer and facilitator test account. And when i login with the facilitator i could see the transactions. 
Thank you for your time.

**Comment by leninchek** [comment]
Hi, sorry for open again this.

But I have the same problem, 
I can see with my facilitator account: https://www.sandbox.paypal.com/
The credit card transactions but I can't see the PayPal transactions

What am I doing wrong?
