### ISSUE TITLE
On Live Site: Class 'PayPal\Core\PPConfigManager' not found

### ISSUE THREAD

**Issue by thom7kick** [anouarabdsslm/laravel-paypalpayment#106]
FatalThrowableError in PaypalPayment.php line 254:
Class 'PayPal\Core\PPConfigManager' not found
@anouarabdsslm

**Comment by al0mie** [comment]
@thom7kick It's because paypal sdk was updated. You can rename it to PayPalConfigManager. Was solved in #96

**Comment by anouarabdsslm** [comment]
@thom7kick we are using now the latest paypal SDK with the last version , try it out.
