### ISSUE TITLE
Requested resource ID was not found

### ISSUE THREAD

**Issue by lodhiyuvraj** [anouarabdsslm/laravel-paypalpayment#107]
I am trying to intigrate paypal then got error 
{"name":"INVALID_RESOURCE_ID","message":"Requested resource ID was not found.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INVALID_RESOURCE_ID","debug_id":"2ec08e9daee0"}

**Comment by anouarabdsslm** [comment]
can you share your peace of code plz

**Comment by anouarabdsslm** [comment]
@lodhiyuvraj will close this for now. But if this issue is still valid you can re-open it and provide some more details.
