### ISSUE TITLE
Shipping address as well as normal address

### ISSUE THREAD

**Issue by nickbluestone98** [anouarabdsslm/laravel-paypalpayment#110]
Hello,

The API is working great for me. I just want to know if there is anyway to set a shipping address separately to the billing address? I really need this functionality! The below code works for address great, but if users ship to a different address how can I achieve this?

```
// ### Address
// Base Address object used as shipping or billing
// address in a payment. [Optional]
$addr = Paypalpayment::address();
$addr->setLine1($billing_address1);
$addr->setLine2($billing_address2);
$addr->setCity($billing_city_district);
$addr->setPostalCode($billing_postcode);
$addr->setCountryCode('GB');
$addr->setPhone($billing_contact_number);	
```
Just to add I know you can do it through the API, just not sure if your Laravel extension supports it with a specific function?

You can do this with the default API syntax:

```
$shipping_address = new ShippingAddress();
$shipping_address->setCity('City');
$shipping_address->setCountryCode('AR');
$shipping_address->setPostalCode('200');
$shipping_address->setLine1('Adress Line1');
$shipping_address->setState('State');
$shipping_address->setRecipientName('Recipient Name');

$itemList->setShippingAddress($shipping_address);
```
Can you let me know if your API supports it?

Kind Regards,

Nick.

**Comment by nickbluestone98** [comment]
Just to add I know you can do it through the API, just not sure if your Laravel extension supports it with a specific function.

You can do this with default API:

```
$shipping_address = new ShippingAddress();
$shipping_address->setCity('City');
$shipping_address->setCountryCode('AR');
$shipping_address->setPostalCode('200');
$shipping_address->setLine1('Adress Line1');
$shipping_address->setState('State');
$shipping_address->setRecipientName('Recipient Name');

$itemList->setShippingAddress($shipping_address);
```

Kind Regards,

Nick.

**Comment by nickbluestone98** [comment]
Just had a good browse through the API's core functions! there is a `shippingAddress();` function which works great!

$shipping_address = Paypalpayment::shippingAddress();

$shipping_address->setRecipientName('TEST NAME');
$shipping_address->setLine1($shipping_address1);
$shipping_address->setLine2($shipping_address2);
$shipping_address->setCity($shipping_city_district);
$shipping_address->setPostalCode($shipping_postcode);
$shipping_address->setCountryCode('GB');
$shipping_address->setPhone($shipping_contact_number);

Hope this helps anyone, facing the issue.

Kind Regards,

Nick.

**Comment by anouarabdsslm** [comment]
@nickbluestone98  thanks for posting the solution here. yes sometimes you just need to check the package core to get answers.
