### ISSUE TITLE
Class Error

### ISSUE THREAD

**Issue by gauravmrvh1** [anouarabdsslm/laravel-paypalpayment#112]
Class 'Services_Twilio' not found

**Comment by binitghetiya** [comment]
@gauravmrvh1 can you please explain more bcz this library is not using Twilio as dependency. please check and explain more.

Thanks

**Comment by anouarabdsslm** [comment]
@gauravmrvh1  as @binitghetiya says we dont use any twilio dependency. this error is related to the missing import for twilion in your app. Try to find where u are using that.
