### ISSUE TITLE
no change to live 

### ISSUE THREAD

**Issue by FranklinStuar** [anouarabdsslm/laravel-paypalpayment#113]
I'm trying publish my page but I've errors. No change from sandbox to live. 

> PayPalConnectionException {
>   -url: "https://api.sandbox.paypal.com/v1/oauth2/token"
>   -data: "{"error":"invalid_client","error_description":"Client Authentication failed"}"
>   #message: "Got Http response code 401 when accessing https://api.sandbox.paypal.com/v1/oauth2/token."
>   #code: 401
>   #file: "/var/www/html/neurocodigo/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php"
> }

The code in paypal_payment is:

- 'EndPoint' => 'https://api.paypal.com',
- 'mode' =>  'live'

The credentials is true, no problem in this code

**Comment by anouarabdsslm** [comment]
@FranklinStuar sorry for the late response. do you have this issue solved if not throw me a snippet of you code to have look.thanks

**Comment by FranklinStuar** [comment]
hello @anouarabdsslm, I solved modifying code directly, but when updating the composer I have to reconfigure again

**Comment by anouarabdsslm** [comment]
@FranklinStuar Can you just open a PR with your fix.

**Comment by anouarabdsslm** [comment]
@FranklinStuar try using  the latest version. you can also check the implementation video tutorial here https://www.youtube.com/watch?v=F67YuGKm220
