### ISSUE TITLE
[ErrorException] Constant PP_CONFIG_PATH already defined

### ISSUE THREAD

**Issue by portalshow** [anouarabdsslm/laravel-paypalpayment#114]
Hello,

After installing the package, it works correctly, but when I execute **PHP ARTISAN ROUTE: LIST** I get the following error:

**[ErrorException]
Constant PP_CONFIG_PATH already defined**

I think it will be because this will be defined in /vendor/paypal/rest-api-sdk-php and in /vendor/anouar/paypalpayment.

If I comment the line 248 in
/vendor/anouar/paypalpayment/src/Anouar/Paypalpayment/PaypalPayment.php:

`// define ("PP_CONFIG_PATH", __DIR__);`

does not cause the error.

Is there another option for not modifying VENDOR files ??

**Comment by anouarabdsslm** [comment]
@portalshow thanks for reporting this a fix for it merged within this PR https://github.com/anouarabdsslm/laravel-paypalpayment/pull/119
