### ISSUE TITLE
Different Card Types

### ISSUE THREAD

**Issue by acedesigns** [anouarabdsslm/laravel-paypalpayment#118]
Hi @anouarabdsslm 

I was trying out the example using Different card Types. So I wrote a little function to detect card type so that I can use it on the following line ....
```php
$card = Paypalpayment::creditCard();
        $card->setType("visa")
```
#### My Code to get card
```php
$detector = new \App\Models\CardDetect();
        $UserCard = '2221000000000009'; // MasterCard :: NOT WORKING
        //$UserCard = '30569309025904'; // Diners Club :: NOT WORKING
        //$UserCard = '4111111111111111'; Visa :: WORKS FINE
        $detection = $detector->detect($UserCard);
```
#### And I used it like this

```php
$card = Paypalpayment::creditCard();
        ->setType(strtolower($detection))
```
## But This Gives me error
```
(1/1) PayPalConnectionException

Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.
```

**Comment by anouarabdsslm** [comment]
@acedesigns sorry for the late response , i think this error thrown when using `Diners Club`. I was able to create successful payment using `mastercard`.For diners i dont know if paypal support it or not , we will need to now the correct type name paypal use for diners if he they support it. For master card just set type to `mastercard` and make sure u use a valid master card, for sanbox try to get one here http://www.getcreditcardnumbers.com.
Creation of payment using `mastercard`
![master_card](https://user-images.githubusercontent.com/2453950/32127575-a949e888-bb6f-11e7-83a3-96d70b181496.png)

**Comment by acedesigns** [comment]
## As a FYI ##
The Master Cards Numbers, that begin with `22` as listed on `https://developer.paypal.com/docs/classic/payflow/payflow-pro/payflow-pro-testing/` return the error mentioned.

![alt text](https://preview.ibb.co/gqwc36/Screen_Shot_2017_10_30_at_09_20_06.png "Logo Title Text 1")


So I used `http://www.getcreditcardnumbers.com/`
