### ISSUE TITLE
no puedo resolver error

### ISSUE THREAD

**Issue by williamsalva** [anouarabdsslm/laravel-paypalpayment#120]
SSL peer handshake failed, the server most likely requires a client certificate to connect
--
in PayPalHttpConnection.php (line 122)
at PayPalHttpConnection->execute('grant_type=client_credentials')in OAuthTokenCredential.php (line 241)

**Comment by anouarabdsslm** [comment]
@williamsalva try using  the latest version. you can also check the implementation video tutorial here https://www.youtube.com/watch?v=F67YuGKm220
