### ISSUE TITLE
Question: When Payment Fails it return only Token, not payment

### ISSUE THREAD

**Issue by webreinvent** [anouarabdsslm/laravel-paypalpayment#127]
Hi Guys,

My question is pretty simple when I create payment using ```$payment->create(Paypalpayment::apiContext());``` it returns me a approval link and ```payment id``` which i store in my db. 

I was expecting when user redirects back irrespective of failure or success, I will receive payment id which I can match with the database entry, instead of payment id, I am getting token [https://i.imgur.com/cJMQ0t3.png](url) which I don't get as one of the parameters while creating the payment. Now, how to match which payment is failed or succeeded or I am missing something?

Thanks

**Comment by anouarabdsslm** [comment]
@webreinvent actually it does send the `token` and `paymentId` as query params. check this video https://www.youtube.com/watch?v=F67YuGKm220
