### ISSUE TITLE
Please update paypal SDK to latest version

### ISSUE THREAD

**Issue by sbthemes** [anouarabdsslm/laravel-paypalpayment#150]
Right now we cant getToken on success payment as this function not available in old paypal SDK.
Can you please update it?
Thanks :)

**Comment by mmejaz** [comment]
Same problem, please ans

**Comment by booleentech** [comment]
> Same problem, please ans

Don't use this as author said its deprecated. Find alternatives or fork and do tweaks as per your need.

**Comment by sbthemes** [comment]
I think this package is deprecated as author mentioned.

**Comment by anouarabdsslm** [comment]
I will update i this weekend when i get some free time
