### ISSUE TITLE
Response Code 400

### ISSUE THREAD

**Issue by arvind132** [anouarabdsslm/laravel-paypalpayment#54]
I have used us account client id and secret ,but still i got the 400 response error ,please guide me.

Thanks in advance

**Comment by imdketav** [comment]
@arvind132 : I am also facing same issue **Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.**

**Comment by xroot** [comment]
@arvind132 try to watch this video to make sure you have implemented the package correctly https://www.youtube.com/watch?v=q5Xb5r4MUB8

**Comment by renjithvk** [comment]
I got the same problem while configuring...

**Comment by pelhage** [comment]
Can @arvind132 confirm if the video @xroot provided solved all issues?

**Comment by pelhage** [comment]
@xroot Does version 1.0 of this package support the latest PHP SDK? I'm using Laravel 4.2, which is why I think there might be issues.

**Comment by pelhage** [comment]
@renjithvk  Have you found a solution?

**Comment by renjithvk** [comment]
I'm re-installed the package and then it solved.

**Comment by rameshsrinivasan** [comment]
I don't get any solution. Please help me.

**Comment by anouarabdsslm** [comment]
@rameshsrinivasan  sorry for the late response guys I had tons of work . what's the issue you're running into ?
