### ISSUE TITLE
What if I want to use other method payment like donation?

### ISSUE THREAD

**Issue by jensej** [anouarabdsslm/laravel-paypalpayment#58]
What if I want to use other method payment like donation?

**Comment by xroot** [comment]
in this case just login to your account and generate a donation button then use that code directly within your app , you don't need to use this package at all.

**Comment by floodedcodeboy** [comment]
@xroot i'm pretty sure @jensej is asking how you would do that using your package and not a donate button. I know i'd certainly like to know. :p

**Comment by psgganesh** [comment]
I am making it even more simpler, at the start am accepting $0.00, they enter what they want, i wanted this to ensure payments big / small can be logged... :smile: 

I think this item can be closed, I feel no action required here...

**Comment by psgganesh** [comment]
lol.. i am testing again 0.0 payments i get 400 response code,, turned out to be bullocks :-1:  guess it depends on the implementation which we do in the end...

**Comment by anouarabdsslm** [comment]
sorry for the delay guys . does this still valid issue. if not I can close it.
