### ISSUE TITLE
Accessing Transactions

### ISSUE THREAD

**Issue by xitude** [anouarabdsslm/laravel-paypalpayment#61]
Could you use this to find details of the transaction by going to a url like 

```
/paypal/{transaction_id}/get
```

Im trying to access transactions on my account via a dashboard.

**Comment by xroot** [comment]
@xitude it up to you how to customize your routes , but you need to write the code that handle this logic yourself , for more details watch this video https://www.youtube.com/watch?v=q5Xb5r4MUB8

**Comment by Gameonn** [comment]
How can I access the transactions details using the transaction id in Laravel 5.2?

**Comment by anouarabdsslm** [comment]
@Gameonn use the transaction id and send get request to the paypal api. I think you can find more details about this in there API doc
