### ISSUE TITLE
$PayerID, not grab from DB!

### ISSUE THREAD

**Issue by onurkose** [anouarabdsslm/laravel-paypalpayment#70]
PayerID is from paypal return value, not some payer id value of your database records.

**Comment by anouarabdsslm** [comment]
does this issue still valid ?

**Comment by onurkose** [comment]
I'll let you know after I check both issues. those are very old from my
previous projects.

------------------------------------------------------------------------
Onur KÖSE

+39 347 757 81 76
+90 533 376 66 48
