### ISSUE TITLE
PayPalInvalidCredentialException in PayPalCredentialManager.php

### ISSUE THREAD

**Issue by hoangphucvu** [anouarabdsslm/laravel-paypalpayment#71]
I have this errors how can i fix it thanks

> PayPalInvalidCredentialException in PayPalCredentialManager.php line 154:
> Credential not found for default user. Please make sure your configuration/APIContext has credential information

**Comment by anouarabdsslm** [comment]
@hoangphucvu can you please watch this video https://www.youtube.com/watch?v=q5Xb5r4MUB8 . let me know if that did not help you solve yr prblm
