### ISSUE TITLE
upgrade Paypal core libraries names

### ISSUE THREAD

**Issue by umefarooq** [anouarabdsslm/laravel-paypalpayment#73]
Please upgrade this package, as Paypal has updated their core libraries names here is one example

PPConfigManager -> PayPalConfigManager and so many other libraries name changed

read here Paypal full changes log

https://github.com/paypal/PayPal-PHP-SDK/blob/82971057e15c067e6269591fad44986041e67d15/release_notes.md

**Comment by anouarabdsslm** [comment]
@umefarooq  sorry for the delay and thanks for mentioning that . would you like take over that . I really have tons of work. I may need to have some other people help to improve this package.
