### ISSUE TITLE
Using a different payment method

### ISSUE THREAD

**Issue by danieljausovec** [anouarabdsslm/laravel-paypalpayment#77]
Hi.

When login to buy with paypal i get this message...i use sandbox account.

`We aren't able to process your payment using your PayPal account at this time. Please go back to merchant and try using a different payment method.`

How to fix this?

**Comment by anouarabdsslm** [comment]
what was the payment method you have used ?

**Comment by danieljausovec** [comment]
PayPal...this message is get on paypal site when i login.
