### ISSUE TITLE
name and expiry date issue

### ISSUE THREAD

**Issue by ravindranath143** [anouarabdsslm/laravel-paypalpayment#78]
Hi anouarabdsslm,

i have followed your tutorial and everything is working fine. but my problem is except card number if i give rest off all values wrong then also it is processing payment. i mean first name , last name , expiry date , cvv etc.. can you please tell me whta can i do.

Thans in advance

**Comment by anouarabdsslm** [comment]
@ravindranath143 Actually this is something handled on paypal side. I cant do anything about it .
