### ISSUE TITLE
How to use item_number or similar

### ISSUE THREAD

**Issue by seldimi** [anouarabdsslm/laravel-paypalpayment#79]
Hey. I have followed  your examples but still face some issues.
I cannot find a way to properly use custom (with setCustom) or item_number.

I don't want to use item SKU or invoice, I want to use custom or item_number as used with POST examples.

I need to verify that payment is made from user and get a custom ID for this order.
I make paymentExecution but the array is too complex to parse (even get transaction has a lot of objects and sub arrays.

Any ideas?

**Comment by anouarabdsslm** [comment]
@seldimi I think this is something you can check on the paypal doc

**Comment by seldimi** [comment]
Well, I couldnt find anything related so was hoping for some help...

**Comment by anouarabdsslm** [comment]
plz take look here https://developer.paypal.com/docs/integration/direct/create-process-order/#create-the-order
