### ISSUE TITLE
Not able to generate the configuration file

### ISSUE THREAD

**Issue by tuhin-paul** [anouarabdsslm/laravel-paypalpayment#83]
I am using Laravel 4. I have followed all the steps mentioned to install this package. But when I reach the part where we have to make changes to the configuration file which needs to be generated through this command `php artisan config:publish anouar/Paypalpayment`, I can't see the file being generated even though the Artisan says: `Configuration published for package: Anouar/Paypalpayment`. I don't see any file generated by the name `paypal_payment.php` anywhere in the entire project directory. Where am I going wrong?

**Comment by anouarabdsslm** [comment]
@tuhin-paul  sorry for the late response . can you watch this video https://www.youtube.com/watch?v=q5Xb5r4MUB8 it will help you setup this package.

**Comment by anouarabdsslm** [comment]
I'm gunna close it and feel free to re-open if that did not solve your problems
