### ISSUE TITLE
What do I need to change to redirect to new layout of Paypal after clicking Buy now button 

### ISSUE THREAD

**Issue by Gameonn** [anouarabdsslm/laravel-paypalpayment#85]
I have executed paypal in my website and it is redirecting it to old layout website, what should I change to redirect to new layout of paypal?

**Comment by anouarabdsslm** [comment]
@Gameonn you can do that by create new instance of the Redirect URL class like so : 
```
$baseUrl = "domain.com";
$redirectUrls = new RedirectUrls();
$redirectUrls->setReturnUrl("$baseUrl/ExecutePayment.php?success=true")
    ->setCancelUrl("$baseUrl/ExecutePayment.php?success=false");
```

**Comment by Gameonn** [comment]
Currently I am just using a paypal form for payment. 
`<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
     <input type="hidden" name="cmd" value="_xclick">
     <input type="hidden" name="hosted_button_id" value="UQGZBANSW9H4S">   
     <input type="hidden" name="item_name" value="Music Cart">
     <input type="hidden" name="item_number" value="M-CART X_{{$order_id}}">
     <input type="hidden" name="amount" id="update-subtotal" value="{{$subtotal}}">
     <input type="hidden" name="currency_code" value="USD">
     <input type="hidden" name="return" value="{{URL::to('/')}}/payment-confirmation">
     <input type="hidden" name="custom" value="{{$order_id}}">
     <input type="hidden" name="rm" value="2">
     <input type="hidden" name="cbt" value="Click here to Complete Order">
     <input type="hidden" name="business" value="erfolg-facilitator@erfolgreicher-sein.com">
     <input type="image" name="submit" border="0" src="https://www.paypalobjects.com/webstatic/en_US/i/btn/png/btn_buynow_107x26.png" alt="Buy Now">
     <img alt="" border="0" width="1" height="1" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" >
</form>`

What I am missing in this?
