### ISSUE TITLE
PayPal Payment suddenly not working any more

### ISSUE THREAD

**Issue by schuesslerf** [anouarabdsslm/laravel-paypalpayment#86]
I have a problem with the payment suddenly, but it worked before and I just don't get it... I just posted the problem on stackoverflow as well: http://stackoverflow.com/questions/40684154/paypal-payment-not-working-any-more-laravel-paypal

Can you maybe help me with that? (Doesn't mind if you answer it here or on stackoverflow)

**Comment by anouarabdsslm** [comment]
@schuesslerf  sorry man for the late response . I was bit busy and did not have much time to check the reported issue. can you please clarify to me what's the error/ exception you get

**Comment by schuesslerf** [comment]
Hello, I now somehow got it fixed and I have no idea why, it seems like some formatting changed the behaviour (and the try-catch-blocks). I don't know why, but however it seems to work now.... I have one other question: Do you know if its possible to enter more then one amount for shipping costs? Like 2.5 for one product, 2.7 for the other, and 9.2 for the third, you know what I mean? Or is this not psosible?

**Comment by anouarabdsslm** [comment]
@schuesslerf  no , but you can count the total  and set it at once when you set the shipping with details object
