### ISSUE TITLE
Examples clarifications

### ISSUE THREAD

**Issue by shigawaka** [anouarabdsslm/laravel-paypalpayment#90]
-I was wondering if I need to create table in DB when using paypal payment?

-In sandboxed mode I need 2 accounts, 1 is for the Buyer and the other is for Seller. Do I need to create another account for the other one or is it automatically processed if details are just filled in?

This is probably a stupid things to ask. Sorry for that

**Comment by anouarabdsslm** [comment]
@shigawaka  buyer is the person going to order your product , seller is the account where the payment should go to when order completed (this is will be paypal account). for sandbox we have created to seller to simulate the recipient of payment  and buyer a demo customer  to work with. does it make sense?

**Comment by shigawaka** [comment]
Ah yes. I figured it out few hours after I post this question. Thanks!
