### ISSUE TITLE
Update your PayPal SDK

### ISSUE THREAD

**Issue by HapLifeMan** [anouarabdsslm/laravel-paypalpayment#92]
Hi, please update the `paypal/rest-api-sdk-php` in your `composer.json` from `1.3.0` to `1.11.0` to prevent SSL issues over HTTPS... I made a pull request https://github.com/anouarabdsslm/laravel-paypalpayment/pull/93 :)

**Comment by anouarabdsslm** [comment]
left you a question there . lets discuss this on the PR  instead
